# Generated by Django 4.0.2 on 2022-06-08 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Activate', 'فعال'), ('Deactivate', 'غیر فعال')], default='Deactivate', max_length=10, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='لینک')),
                ('description', models.TextField(null=True, verbose_name='متن مقاله')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d', verbose_name='عکس')),
                ('read_time', models.IntegerField(default=1)),
                ('visite', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='AskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='سوال')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال های پرتکرار',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CategoryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=255, verbose_name='لینک دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('comment', models.TextField(max_length=400)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articleclass')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('title', models.CharField(max_length=150)),
                ('comment', models.TextField(max_length=400)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DjangoRoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoTricks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_video', models.CharField(max_length=255, verbose_name='نام ویدیو')),
                ('id_video', models.CharField(max_length=255, verbose_name='آیدی ویدیو')),
                ('src', models.TextField(verbose_name='آدرس ویدیو')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update', models.DateField(auto_now=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='DjangoTricksDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=50, unique=True)),
                ('random_url', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('r_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پاسخ کامنت',
                'verbose_name_plural': 'پاسخ کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_on', models.DateTimeField(auto_now=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.articleclass')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک ها',
            },
        ),
        migrations.CreateModel(
            name='IpUserToView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, default='None', max_length=225, null=True, verbose_name='نام کاربر')),
                ('userIp', models.CharField(default='000,000,000,000', max_length=15, verbose_name='IP کاربر')),
                ('date_visite', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articleclass', verbose_name='آیتم؟')),
            ],
            options={
                'verbose_name': 'آدرس IP کاربر',
                'verbose_name_plural': 'آدرس های IP کاربران',
            },
        ),
        migrations.AddField(
            model_name='articleclass',
            name='category',
            field=models.ManyToManyField(to='blog.CategoryClass', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='articleclass',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
