# Generated by Django 4.0.2 on 2022-02-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleclass',
            options={'ordering': ('-created',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
