# Generated by Django 4.0.2 on 2022-06-08 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSourceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Activate', 'فعال'), ('Deactivate', 'غیر فعال')], default='Deactivate', max_length=10, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان پروژه')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='لینک')),
                ('description', models.TextField(null=True, verbose_name='متن پروژه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d', verbose_name='عکس')),
                ('visite', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
                'ordering': ('-created',),
            },
        ),
    ]
