# Generated by Django 4.0.2 on 2022-02-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articleclass_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoTricks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_video', models.CharField(max_length=255, verbose_name='نام ویدیو')),
                ('id_video', models.CharField(max_length=255, verbose_name='آیدی ویدیو')),
                ('src', models.TextField(verbose_name='آدرس ویدیو')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update', models.DateField(auto_now=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ('-created',),
            },
        ),
    ]
