# Generated by Django 4.0.2 on 2022-03-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_askedquestions_alter_articleclass_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArticleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=255, verbose_name='لینک دسته بندی')),
            ],
        ),
    ]
