# Generated by Django 4.0.2 on 2022-03-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categoryarticleclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclass',
            name='category',
            field=models.ManyToManyField(to='blog.CategoryArticleClass', verbose_name='دسته بندی'),
        ),
    ]
