# Generated by Django 4.0.2 on 2022-03-05 19:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_categoryarticleclass_categoryclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoRoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
