# Generated by Django 4.0.2 on 2022-03-05 20:07

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_djangoroadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoroadmap',
            name='text',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
