# Generated by Django 4.0.2 on 2022-03-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_articleclass_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclass',
            name='status',
            field=models.CharField(choices=[('Activate', 'فعال'), ('Deactivate', 'غیر فعال')], default='Deactivate', max_length=10, verbose_name='وضعیت'),
        ),
    ]
