# Generated by Django 4.0.2 on 2022-03-13 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_alter_articleclass_user_alter_djangotricks_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleclass',
            options={'ordering': ('-created',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='articleclass',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='articleclass',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='djangotricks',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='آخرین آپدیت'),
        ),
    ]
