# Generated by Django 4.0.2 on 2022-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_articleclass_options_alter_articleclass_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoroadmap',
            name='text',
            field=models.TextField(),
        ),
    ]
