# Generated by Django 4.0.2 on 2022-03-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_djangoroadmap_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoroadmap',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
