# Generated by Django 4.0.2 on 2022-04-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_djangoroadmap_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_user', models.GenericIPAddressField(verbose_name='آیپی کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='articleclass',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='visits', to='blog.IpAddress', verbose_name='تعداد بازدید مقاله'),
        ),
    ]
