# Generated by Django 4.0.2 on 2022-04-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_ip_user_ipaddress_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='ip_address',
            new_name='ip_user',
        ),
    ]
