# Generated by Django 4.0.2 on 2022-04-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_ip_address_ipaddress_ip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclass',
            name='visits',
            field=models.ManyToManyField(blank=True, null=True, related_name='visits', to='blog.IpAddress', verbose_name='تعداد بازدید مقاله'),
        ),
    ]
