# Generated by Django 4.0.2 on 2022-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_ip_user_ipaddress_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclass',
            name='visits',
            field=models.ManyToManyField(null=True, related_name='visits', to='blog.IpAddress', verbose_name='تعداد بازدید مقاله'),
        ),
    ]
