# Generated by Django 4.0.2 on 2022-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_articleclass_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclass',
            name='visits',
            field=models.ManyToManyField(default=1, null=True, related_name='visits', to='blog.IpAddress', verbose_name='تعداد بازدید مقاله'),
        ),
    ]
