# Generated by Django 4.0.2 on 2022-04-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_articleclass_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclass',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='visits', to='blog.IpAddress', verbose_name='تعداد بازدید مقاله'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='آیپی کاربر'),
        ),
    ]
