# Generated by Django 4.0.2 on 2022-04-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_ipaddress_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='آیپی کاربر'),
        ),
    ]
