# Generated by Django 4.0.2 on 2022-04-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclass',
            name='category',
            field=models.ManyToManyField(null=True, to='blog.CategoryClass', verbose_name='دسته بندی'),
        ),
    ]
