# Generated by Django 4.0.2 on 2022-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_articleclass_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclass',
            name='category',
            field=models.ManyToManyField(to='blog.CategoryClass', verbose_name='دسته بندی'),
        ),
    ]
