# Generated by Django 4.0.2 on 2022-05-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_articleclass_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleclass',
            name='visits',
        ),
        migrations.DeleteModel(
            name='IpAddress',
        ),
    ]
