# Generated by Django 4.0.2 on 2022-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_articleclass_visits_delete_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclass',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
