# Generated by Django 4.0.2 on 2022-05-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_articleclass_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleclass',
            name='ip_address',
        ),
        migrations.CreateModel(
            name='PostViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='192.168.1.1')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articleclass')),
            ],
        ),
    ]
