# Generated by Django 4.0.2 on 2022-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Activate', 'فعال'), ('Deactivate', 'غیر فعال')], default='Deactivate', max_length=10, verbose_name='وضعیت'),
        ),
    ]
