# Generated by Django 4.0.2 on 2022-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='admin@test.com', max_length=254),
        ),
    ]
