# Generated by Django 4.0.2 on 2022-05-17 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_comment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoTricksDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=50, unique=True)),
                ('random_url', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.DeleteModel(
            name='PostViews',
        ),
    ]
