# Generated by Django 4.0.2 on 2022-05-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_replycomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='comment',
            new_name='r_comment',
        ),
    ]
