# Generated by Django 4.0.2 on 2022-05-27 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryclass',
            options={'verbose_name': 'category', 'verbose_name_plural': "category's"},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['created_on'], 'verbose_name': 'contact us', 'verbose_name_plural': 'contact us'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='title',
            field=models.CharField(max_length=150),
            preserve_default=False,
        ),
    ]
